allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: Rule
port: 7890
proxies:
- cipher: aes-256-gcm
  name: JMS-731341@c90s1.portablesubmarines.com:15325
  password: 9GfXqoYsCCGkogps
  port: 15325
  server: 104.225.238.209
  type: ss
- cipher: aes-256-gcm
  name: JMS-731341@c90s2.portablesubmarines.com:15325
  password: 9GfXqoYsCCGkogps
  port: 15325
  server: 104.225.156.211
  type: ss
- alterId: 0
  cipher: auto
  name: JMS-731341@c90s3.portablesubmarines.com:15325
  network: tcp
  port: 15325
  server: 198.181.43.95
  type: vmess
  uuid: 35900538-d931-4000-88ae-4751e9784470
- alterId: 0
  cipher: auto
  name: JMS-731341@c90s4.portablesubmarines.com:15325
  network: tcp
  port: 15325
  server: 45.78.58.111
  type: vmess
  uuid: 35900538-d931-4000-88ae-4751e9784470
- alterId: 0
  cipher: auto
  name: JMS-731341@c90s5.portablesubmarines.com:15325
  network: tcp
  port: 15325
  server: 162.248.74.168
  type: vmess
  uuid: 35900538-d931-4000-88ae-4751e9784470
- alterId: 0
  cipher: auto
  name: JMS-731341@c90s801.portablesubmarines.com:15325
  network: tcp
  port: 15325
  server: 104.225.152.34
  type: vmess
  uuid: 35900538-d931-4000-88ae-4751e9784470
proxy-groups:
- name: PROXY
  proxies:
  - DIRECT
  - JMS-731341@c90s1.portablesubmarines.com:15325
  - JMS-731341@c90s2.portablesubmarines.com:15325
  - JMS-731341@c90s3.portablesubmarines.com:15325
  - JMS-731341@c90s4.portablesubmarines.com:15325
  - JMS-731341@c90s5.portablesubmarines.com:15325
  - JMS-731341@c90s801.portablesubmarines.com:15325
  type: select
- interval: 300
  name: Auto
  proxies:
  - JMS-731341@c90s1.portablesubmarines.com:15325
  - JMS-731341@c90s2.portablesubmarines.com:15325
  - JMS-731341@c90s3.portablesubmarines.com:15325
  - JMS-731341@c90s4.portablesubmarines.com:15325
  - JMS-731341@c90s5.portablesubmarines.com:15325
  - JMS-731341@c90s801.portablesubmarines.com:15325
  type: url-test
  url: http://www.gstatic.com/generate_204
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- GEOIP,CN,DIRECT
- MATCH,PROXY
socks-port: 7891
