allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: Rule
port: 7890
proxies:
- cipher: aes-256-gcm
  name: JMS-1268850@c83s1.portablesubmarines.com:15130
  password: c5Tc3F7W44WcBdED
  port: 15130
  server: 104.160.41.123
  type: ss
- cipher: aes-256-gcm
  name: JMS-1268850@c83s2.portablesubmarines.com:15130
  password: c5Tc3F7W44WcBdED
  port: 15130
  server: 104.160.44.223
  type: ss
- alterId: 0
  cipher: auto
  name: JMS-1268850@c83s3.portablesubmarines.com:15130
  network: tcp
  port: 15130
  server: 198.181.44.203
  type: vmess
  uuid: ddf88f41-c23e-46a0-80fa-062bb90bc848
- alterId: 0
  cipher: auto
  name: JMS-1268850@c83s4.portablesubmarines.com:15130
  network: tcp
  port: 15130
  server: 23.106.141.34
  type: vmess
  uuid: ddf88f41-c23e-46a0-80fa-062bb90bc848
- alterId: 0
  cipher: auto
  name: JMS-1268850@c83s5.portablesubmarines.com:15130
  network: tcp
  port: 15130
  server: 104.193.8.40
  type: vmess
  uuid: ddf88f41-c23e-46a0-80fa-062bb90bc848
- alterId: 0
  cipher: auto
  name: JMS-1268850@c83s801.portablesubmarines.com:15130
  network: tcp
  port: 15130
  server: 45.62.104.100
  type: vmess
  uuid: ddf88f41-c23e-46a0-80fa-062bb90bc848
proxy-groups:
- name: PROXY
  proxies:
  - DIRECT
  - JMS-1268850@c83s1.portablesubmarines.com:15130
  - JMS-1268850@c83s2.portablesubmarines.com:15130
  - JMS-1268850@c83s3.portablesubmarines.com:15130
  - JMS-1268850@c83s4.portablesubmarines.com:15130
  - JMS-1268850@c83s5.portablesubmarines.com:15130
  - JMS-1268850@c83s801.portablesubmarines.com:15130
  type: select
- interval: 300
  name: Auto
  proxies:
  - JMS-1268850@c83s1.portablesubmarines.com:15130
  - JMS-1268850@c83s2.portablesubmarines.com:15130
  - JMS-1268850@c83s3.portablesubmarines.com:15130
  - JMS-1268850@c83s4.portablesubmarines.com:15130
  - JMS-1268850@c83s5.portablesubmarines.com:15130
  - JMS-1268850@c83s801.portablesubmarines.com:15130
  type: url-test
  url: http://www.gstatic.com/generate_204
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- GEOIP,CN,DIRECT
- MATCH,Auto
socks-port: 7891
